version: '3.6'

networks:
  test:
    name: fabric_net


services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      - MYSQL_PASSWORD=mglFuture7@$$
      - MYSQL_ROOT_PASSWORD=mglFuture7@$$
      - MYSQL_DATABASE=mgldefi

    ports:
      - '3306:3306'
    networks:
      - test
    volumes:
      - ./database:/var/lib/mysql